<!DOCTYPE html>
<html>
<head>
    <!-- Get meta -->
    <?= $this->tag->tagHtml('meta', ['charset' => 'UTF-8']) . PHP_EOL; ?>
    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">
    <meta name="generator" content="Phalcon">
    <meta name="author" content="Stanislav WEB">
    <meta http-equiv="Cache-Control" content="public">
    <meta http-equiv="Cache-Control" content="max-age=99090600, must-revalidate">
    <link rel="shortcut icon" type="image/vnd.microsoft.icon" href="/assets/favicon.ico"/>
    <?= $this->tag->getTitle(); ?>
    <!-- /Get meta -->
    <!-- Append Stylesheet -->
    <?= $this->tag->stylesheetLink("https://maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap.min.css", false); ?>
    <?= $this->tag->stylesheetLink("http://maxcdn.bootstrapcdn.com/font-awesome/4.2.0/css/font-awesome.min.css", false); ?>
    <?= $this->tag->stylesheetLink("http://fonts.googleapis.com/css?family=Righteous", false); ?>
    <?= $this->tag->stylesheetLink('assets/plugins/jquery-ui/jquery-ui.css'); ?>
    <?= $this->tag->stylesheetLink('assets/backend/css/style.css'); ?>
    <!-- /Append Stylesheet -->

    <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
    <?=$this->tag->javascriptInclude("https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js", false); ?>
    <?=$this->tag->javascriptInclude("https://oss.maxcdn.com/respond/1.4.2/respond.min.js", false); ?>
    <![endif]-->
</head>
<body>
<!-- Content -->
<?php echo $this->getContent() ?>
<!-- /Content -->
</body>
</html>