<div class="row">
    <div class="col-xs-12">
        <div class="box-conten no-padding">

            <!-- Add Auth form -->
            <?= $this->tag->form(['id' => 'sign', 'class' => 'form-horizontal', 'method' => 'post']); ?>
            <div class="form-group">
                <label for="name" class="control-label col-sm-3">Login</label>

                <div class="col-sm-6">
                    <?= $form->render('login', [
                        'placeholder' => 'Input login',
                        'class' => 'form-control',
                    ]); ?>
                </div>
            </div>

            <div class="form-group">
                <label for="description" class="control-label col-sm-3">Password</label>
                <div class="col-sm-6">
                    <?= $form->render('password', [
                        'class' => 'col-sm-5 form-control',
                    ]); ?>
                </div>
            </div>


            <div class="form-group">
                <div class="col-sm-3"></div>
                <div class="col-sm-6 ">
                    <?= $form->render('auth', ['value' => 'Sign in', 'class' => 'btn btn-primary btn-lg btn-block']); ?>
                </div>
            </div>
            </form>
            <!-- /Add Auth form -->
        </div>
    </div>
</div>