<!-- Start Top -->
<?php $this->partial("dashboard/top", ['user' => $user]) ?>
<!-- /End Top -->

<!--Start Container-->
<div id="main" class="container-fluid">
	<div class="row">
		<!-- Start Sidebar -->
		<?php $this->partial("dashboard/sidebar") ?>
		<!-- /End Sidebar -->

		<!--Start Content-->
		<!--<div id="content" class="col-xs-12 col-sm-10">
			<div id="about">
				<div class="about-inner">
					<h4 class="page-header">Open-source admin theme for you</h4>
					<p>DevOOPS team</p>
					<p>Homepage - <a href="http://devoops.me" target="_blank">http://devoops.me</a></p>
					<p>Email - <a href="mailto:devoopsme@gmail.com">devoopsme@gmail.com</a></p>
					<p>Twitter - <a href="http://twitter.com/devoopsme" target="_blank">http://twitter.com/devoopsme</a></p>
					<p>Donate - BTC 123Ci1ZFK5V7gyLsyVU36yPNWSB5TDqKn3</p>
				</div>
			</div>
			<div class="preloader">
				<img src="img/devoops_getdata.gif" class="devoops-getdata" alt="preloader"/>
			</div>
			<div id="ajax-content"></div>
		</div>
		<!--End Content
		-->
	</div>
</div>
<!--/End Container-->>

