<div id="pbmContentBody">
    <p>If you're financially unable to pay your tax debt immediately, you can make <b>monthly payments</b> through an installment agreement. As long as you pay your tax debt in full, you can reduce or eliminate your payment of penalties or interest, and avoid the fee associated with setting up the agreement.</p>

    <p>Before applying for any payment agreement, <b>you must file all required tax returns.</b></p>

    <h3>You may be eligible to apply for an online payment agreement</h3>

    <ul>
        <li class="first-child">Individuals must owe $50,000 or less in combined individual income tax, penalties and interest, and have filed all required returns.</li>

        <li>Businesses must owe $25,000 or less in payroll taxes and have filed all required returns.</li>

        <li>If you meet these requirements, you can apply for an <a href="/Individuals/Online-Payment-Agreement-Application">online payment agreement</a>.</li>

        <li class="last-child"><b>Please note:</b> If you file joint tax returns with your spouse, you may be unable to complete your installment agreement request using this application. <a href="/Individuals/Eligibility-Issue-with-the-Online-Payment-Agreement-Application">Please click here for more information</a>.</li>
    </ul>

    <h3>Even if you're ineligible for an online payment agreement, you can still pay in installments</h3>

    <ul>
        <li class="first-child">Complete and mail <a href="/file_source/pub/irs-pdf/f9465.pdf" onclick="_gaq.push(['_trackEvent', 'Downloads', 'File Download', '/file_source/pub/irs-pdf/f9465.pdf']);">Form 9465, Installment Agreement Request</a> (PDF)&nbsp;and <a href="/file_source/pub/irs-pdf/f433f.pdf" onclick="_gaq.push(['_trackEvent', 'Downloads', 'File Download', '/file_source/pub/irs-pdf/f433f.pdf']);">Form 433-F, Collection Information Statement</a> (PDF);</li>

        <li class="last-child">Call 800-829-1040 or the phone number on your bill or notice</li>
    </ul>

    <h3>Small Businesses can apply for an in-Business Trust Fund Express installment agreement</h3>

    <ul>
        <li class="first-child">Call the IRS Business and Specialty Tax assistance line 800-829-4933;</li>

        <li>Call the phone number on your bill or notice;</li>

        <li class="last-child">More information</li>
    </ul>

    <h3>Understand your agreement &amp; avoid default</h3>

    <ul>
        <li class="first-child">Your future refunds will be applied to your tax debt until it is paid in full;</li>

        <li>Pay at least your minimum monthly payment when it's due;</li>

        <li>Include your name, address, SSN, daytime phone number, tax year and return type on your payment;</li>

        <li>File all required tax returns on time &amp; pay all taxes in-full and on time (contact us to change your existing agreement if you cannot);</li>

        <li>Make all scheduled payments even if we apply your refund to your account balance; and</li>

        <li class="last-child">Ensure your statement is sent to the correct address, contact us if you move or complete and mail <a href="/file_source/pub/irs-pdf/f8822.pdf" onclick="_gaq.push(['_trackEvent', 'Downloads', 'File Download', '/file_source/pub/irs-pdf/f8822.pdf']);">Form 8822, Change of Address</a> (PDF).</li>
    </ul>

    <p>If you don't receive your statement, send your payment to the address listed in your agreement.</p>

    <p>There may be a reinstatement fee if your agreement goes into default. Penalties and interest continue to accrue until your balance is paid in full. If you are in danger of defaulting on your payment agreement for any reason, contact us immediately. We will generally not take <a href="/Businesses/Small-Businesses-&amp;-Self-Employed/Enforced-Collection-Actions">enforced collection actions</a>:</p>

    <ul>
        <li class="first-child">When an installment agreement is being considered;</li>

        <li>While an agreement is in effect;</li>

        <li>For 30 days after a request is rejected, or</li>

        <li class="last-child">During the period the IRS evaluates an appeal of a rejected or terminated agreement.</li>
    </ul>
    <div id="advantages">This is advantages terms</div>
</div>