<div id="content" class="grid_6">
<!--googleon: all-->


<div>










<!-- Start of List (Ordered) type List -->




<!--googleoff: all-->
<div class="tools">
    <!-- new Like tracking -->
    <span title="Like" class="like" onclick="javascript:addBookmark(location.href, document.title); _gaq.push(['_trackEvent', 'Heart Button', 'Bookmark', 'Like']);">Like - Click this link to Add this page to your bookmarks</span>
    <!-- new share tracking -->

    <!-- AddThis Button BEGIN -->
    <a class="share addthis_button" href="http://apps.irs.gov/app/scripts/exit.jsp?dest=http://addthis.com/bookmark.php?v=250" title="Share" onclick="_gaq.push(['_trackEvent', 'Outbound Links', 'Click', 'addthis.com/bookmark.php?v=250']);">Share - Click this link to Share this page through email or social media</a>


    <script type="text/javascript">
        var addthis_config = {
            data_ga_property: 'UA-22588183-6',
            data_ga_social: true
        };
    </script>
    <script type="text/javascript" src="http://s7.addthis.com/js/250/addthis_widget.js"></script>
    <!-- AddThis Button END -->


    <!-- New print tracking -->
		<span title="Print" class="print" onclick="javascript:window.print();
		_gaq.push(['_trackEvent', 'Print Button', 'Print', ' Print Page']);">Print - Click this link to Print this page</span>
    <!-- new Print tracking -->

</div>
<!--googleon: all-->



<h1>How to Contact the IRS</h1>
















































<p>
    <a href="/Refunds/Where's-My-Refund-It's-Quick,-Easy,-and-Secure." class="title">Where's My Refund? will give you personalized refund information</a><br> The IRS issues more than 9 out of 10 refunds in less than 21 days. Where’s My Refund? has the most up to date information available about your refund. The tool is updated once a day so you don’t need to check more often. IRS representatives can research the status of your refund only if you’ve already checked Where’s My Refund? and it’s been 21 days or more since you filed electronically, more than six weeks since you mailed your paper return, or if Where’s My Refund? directs you to contact us.

</p>

































<p>
    <a href="/uac/Suspicious-e-Mails-and-Identity-Theft" class="title">Suspicious e-Mails, Phishing, and Identity Theft</a><br> The IRS does not send out unsolicited e-mails asking for personal information.  An electronic mailbox has been established for you to report suspicious e-mails claiming to have been sent by the IRS.


</p>



















































<p>
    <a href="/Individuals/How-Do-You-Report-Suspected-Tax-Fraud-Activity%3F" class="title">How Do You Report Suspected Tax Fraud Activity?</a><br> If you have information about an individual or company you suspect is not complying with the tax law, report this activity.
</p>




































<p>
    <a href="/uac/Contact-Your-Local-IRS-Office-1" class="title">Contact Your Local IRS Office</a><br> IRS Taxpayer Assistance Centers are available for when you believe your issue is best handled face-to-face. Before you visit, check hours and services offered. Return preparation services are no longer available at your local IRS office. Use IRS Free File, free brand-name software that will figure your taxes for you. Or visit the nearest volunteer site for free help preparing and e-filing your tax return.
</p>

































<p>
    <a href="/uac/Where-to-File-Paper-Tax-Returns-With-or-Without-a-Payment" class="title">IRS Mailing Addresses ("Where to File")</a><br> For those who don't file their federal tax returns electronically, the "Where to File" pages provide mailing addresses for filing all paper tax returns. You may also use your appropriate "Where to File" address for other written correspondence with the IRS.
</p>

































<p>
    <a href="/Advocate/Local-Taxpayer-Advocate/Contact-Your-Local-Taxpayer-Advocate" class="title">Contact Your Taxpayer Advocate</a><br> If you have an ongoing issue with the IRS that has not been resolved through normal processes, or you have suffered, or are about to suffer a significant hardship/economic burden as a result of the administration of the tax laws, contact the Taxpayer Advocate Service. We have offices in all 50 states, the District of Columbia, and Puerto Rico.
</p>















































<p>
    <a href="/uac/How-to-Make-an-Offshore-Voluntary-Disclosure" class="title">How to Make an Offshore Voluntary Disclosure </a><br> Taxpayers wanting to report undisclosed income or assets should come in through the IRS Voluntary Disclosure Program.
</p>




































<p>
    <a href="/Individuals/HCTC:-Contact-Us" class="title">Contact the Health Coverage Tax Credit Program</a><br> The legislation that authorized the Health Coverage Tax Credit (HCTC) expired January 1, 2014. This tax credit helped make health insurance more affordable for eligible individuals and their families by paying a significant portion of qualified health insurance premiums for tax years 2002 through 2013.
</p>
















































<p>
    <a href="/Tax-Professionals/Contact-the-IRS-Return-Preparer-Program" class="title">Contact the IRS Return Preparer Program</a><br> PTIN call center phone numbers.  These phone numbers are for tax professionals only and DO NOT provide assistance with individual income tax return or refund issues

</p>

































<p>
    <a href="/uac/Contact-My-Local-Office-Internationally" class="title">Contact IRS Internationally</a><br> International Services: IRS contact information for taxpayers who live outside the United States.
</p>


















































<p>
    <a href="/uac/Navigate-IRSgov" class="title">Navigate IRS.gov</a><br> Get help navigating the site, finding information, using site features or understanding file formats. Chat or speak with a website customer service representative or send an email message or comment. Website assistance is available Monday-Friday.
</p>



<!--googleoff: all-->
<div class="modified">Page Last Reviewed or Updated: 23-Dec-2014</div>
<!--googleon: all-->



</div>


<!--googleoff: all-->


</div>