<!DOCTYPE html>
<html ng-app="<?=strtolower($engine['code']);?>">
    <head>
        <!-- Get meta -->
        <?= $this->tag->tagHtml('meta', ['charset' => 'UTF-8']) . PHP_EOL; ?>
        <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">
        <meta http-equiv="Cache-Control" content="public">
        <meta http-equiv="Cache-Control" content="max-age=99090600, must-revalidate">
        <link rel="shortcut icon" type="image/vnd.microsoft.icon" href="/assets/favicon.ico"/>
        <?= $this->tag->getTitle(); ?>
        <!-- /Get meta -->

        <!-- Append Stylesheet -->
        <?php if (APPLICATION_ENV == 'production'): ?>
        <?php else: ?>
        <?php endif; ?>
        <!-- /Append Stylesheet -->

        <!-- Javascript area content -->
        <?php if (APPLICATION_ENV == 'production'): ?>
            <?=$this->tag->javascriptInclude("https://ajax.googleapis.com/ajax/libs/angularjs/1.3.8/angular.min.js", false); ?>
            <?=$this->tag->javascriptInclude("https://ajax.googleapis.com/ajax/libs/angularjs/1.3.8/angular-route.min.js", false); ?>
        <?php else: ?>
            <?= $this->tag->javascriptInclude("assets/plugins/angular/angular.min.js", true);  // local ?>
            <?= $this->tag->javascriptInclude("assets/plugins/angular/angular-route.min.js", true);  // local ?>
        <?php endif; ?>
        <?= $this->tag->javascriptInclude("assets/frontend/".strtolower($engine['code'])."/app.js", true);  // local ?>
        <?= $this->tag->javascriptInclude("assets/frontend/".strtolower($engine['code'])."/controllers.js", true);  // local ?>
        <!-- /Javascript area content -->

        <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
        <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
        <!--[if lt IE 9]>
        <?=$this->tag->javascriptInclude("https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js", false); ?>
        <?=$this->tag->javascriptInclude("https://oss.maxcdn.com/respond/1.4.2/respond.min.js", false); ?>
        <![endif]-->
    </head>
    <body>
        <!-- Content -->
        <?php echo $this->getContent() ?>
        <!-- /Content -->
        <?= (isset($toolbar) === true) ? $toolbar->render() : ''; ?>
    </body>
</html>