<!DOCTYPE html>
<html ng-app="<?=strtolower($engine['code']);?>">
    <head>
        <base href="/">
        <!-- Get meta -->
        <?= $this->tag->tagHtml('meta', ['charset' => 'UTF-8']) . PHP_EOL; ?>
        <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">
        <meta http-equiv="Cache-Control" content="public">
        <meta http-equiv="Cache-Control" content="max-age=99090600, must-revalidate">
        <link rel="shortcut icon" type="image/vnd.microsoft.icon" href="/assets/favicon.ico"/>
        <meta name="token" title="<?= $this->security->getTokenKey() ?>" content="<?= $this->security->getToken() ?>"/>
        <?= $this->tag->getTitle(); ?>
        <!-- /Get meta -->

        <!-- Append Stylesheet -->
            <?php $this->assets->outputCss('header-css'); ?>
        <!-- /Append Stylesheet -->

        <!-- Javascript area content -->
            <?php $this->assets->outputJs('header-js'); ?>
        <!-- /Javascript area content -->

        <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
        <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
        <!--[if lt IE 9]>
        <?=$this->tag->javascriptInclude("https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js", false); ?>
        <?=$this->tag->javascriptInclude("https://oss.maxcdn.com/respond/1.4.2/respond.min.js", false); ?>
        <![endif]-->
    </head>
    <body>
        <!-- Content -->
        <?php echo $this->getContent() ?>
        <!-- /Content -->
        <?php $this->assets->outputJs('footer-js'); ?>
    </body>
</html>