<!-- Dashboard header -->
<div id="dashboard-header" class="row">
	<div class="col-xs-10 col-sm-4">
		<h3><i class="fa fa-database fa-md"></i> <b><?=$title;?> storage</b></h3>
	</div>
</div>
<!-- /Dashboard header -->

<!-- Dashboard content -->
<?php if((float)$server['stats']['cmd_get'] != 0):?>
	<?php
	$percentHit = ((float)$server['stats']['get_hits']/(float)$server['stats']['cmd_get']*100);
	?>
<?php else: ?>
	<?php $percentHit = 0;?>
<?php endif;?>
<?php $percentMiss = 100-(round(0,3)); ?>
<div class="row-fluid">
	<div id="dashboard_links" class="col-xs-12 col-sm-2 pull-right">
		<ul class="nav nav-pills nav-stacked">
			<li class="active"><a href="#server" class="tab-link" id="server">Server info</a></li>
			<li><a href="#pool" class="tab-link" id="pool">Pool data</a></li>
			<li><a href="#statistics" class="tab-link" id="statistics">Charts</a></li>
			<li><a href="#adapter" class="tab-link" id="adapter">Adapter config</a></li>
		</ul>
	</div>
	<div id="dashboard_tabs" class="col-xs-12 col-sm-10">
		<div id="dashboard-server" name="server" class="row padding-15" style="visibility: visible; position: relative;">
			<div class="col-xs-12 col-md-12">
				<table class="table m-table table-bordered table-hover table-heading">
					<thead>
					<tr>
						<th colspan="2"><b><?=$title;?> storage</b></th>
					</tr>
					</thead>
					<tbody>
						<tr>
							<td class="m-ticker">State</td>
							<td class="m-price col-md-4">
								<?php if($server['status'] == 1): ?>
									<button class="btn-sm btn btn-success" disabled>UP</button>
								<?php else: ?>
									<button class="btn-sm btn btn-danger" disabled>DOWN</button>
								<?php endif;?>
							</td>
						</tr>
						<tr>
							<td class="m-ticker">Memcache Server version</td>
							<td class="m-price"><?=$server['stats']['version'];?></td>
						</tr>
						<tr>
							<td class="m-ticker">IP : Port</td>
							<td class="m-price">
								<?=(isset($server['host'])) ? $server['host'] : 'unknown' ;?> : <?=(isset($server['port'])) ? $server['port'] : 'unknown' ;?>
							</td>
						</tr>
						<tr>
							<td class="m-ticker">Server Uptime</td>
							<td class="m-price"><?=Helpers\Format::timestampToDate($server['stats']['uptime']);?></td>
						</tr>
						<tr>
							<td class="m-ticker">Max cache size</td>
							<td class="m-price"><?=Helpers\Format::formatBytes($server['stats']['limit_maxbytes'],2);?></td>
						</tr>
						<tr>
							<td class="m-ticker">Used cache size</td>
							<td class="m-price"><?=Helpers\Format::formatBytes($server['stats']['bytes'],2);?></td>
						</tr>
						<tr>
							<td class="m-ticker">Available cache size</td>
							<td class="m-price">
								<?=Helpers\Format::formatBytes($server['stats']['limit_maxbytes']-$server['stats']['bytes'],2);?>
							</td>
						</tr>
						<tr>
							<td class="m-ticker">Number of open connections</td>
							<td class="m-price"><?=$server['stats']['curr_connections'];?></td>
						</tr>
						<tr>
							<td class="m-ticker">Total number of items stored by this server ever since it started</td>
							<td class="m-price"><?=$server['stats']['total_items'];?></td>
						</tr>
						<tr>
							<td class="m-ticker">Total number of connections opened since the server started running</td>
							<td class="m-price"><?=$server['stats']['total_connections'];?></td>
						</tr>
						<tr>
							<td class="m-ticker">Cumulative number of retrieval requests</td>
							<td class="m-price"><?=$server['stats']['cmd_get'];?></td>
						</tr>
						<tr>
							<td class="m-ticker">Cumulative number of storage requests</td>
							<td class="m-price"><?=$server['stats']['cmd_set'];?></td>
						</tr>
						<tr>
							<td class="m-ticker">Number of keys that have been requested and found present</td>
							<td class="m-price"><?=$server['stats']['get_hits'];?> (<?=number_format($percentHit);?>%)</td>
						</tr>
						<tr>
							<td class="m-ticker">Number of items that have been requested and not found</td>
							<td class="m-price"><?=$server['stats']['get_misses'];?> (<?=number_format($percentMiss);?>%)</td>
						</tr>
						<tr>
							<td class="m-ticker">Total number of bytes read by this server from network</td>
							<td class="m-price"><?=Helpers\Format::formatBytes($server['stats']['bytes_read'],2);?></td>
						</tr>
						<tr>
							<td class="m-ticker">Number of valid items removed from cache to free memory for new items</td>
							<td class="m-price"><?=$server['stats']['evictions'];?></td>
						</tr>
					</tbody>
				</table>
			</div>
		</div>

		<div id="dashboard-pool" name="pool" class="row padding-15" style="visibility: hidden; position: absolute;">
			<div class="col-xs-12 col-md-6">
				<div class="btn-group btn-group-justified">
					<div class="btn-group">
						<a class="btn btn-info" href="#" onclick="Common.filter(); return false;">Refresh</a>
					</div>
					<div class="btn-group">
						<a class="btn btn-primary" href="#" onclick="Common.doublePrompt('Set key', 'Set value', '/set'); return false;">SET</a>
					</div>
					<div class="btn-group">
						<a class="btn btn-danger" href="#" onclick="Common.confirm('Are you sure?', '/flush'); return false;">FLUSH</a>
					</div>
				</div>
			</div>
			<div class="clearfix"></div>

			<div class="table-responsive">
				<table id="stored_keys" class="table-striped table-bordered table-hover  table-heading">
					<thead>
						<tr>
							<th class="col-md-4">Key</th>
							<th class="col-md-4">Value</th>
							<th class="col-md-2">Data size</th>
							<th class="col-md-1">Type</th>
							<th class="col-md-1">Action</th>
						</tr>
					</thead>
					<tbody>
					<?php foreach($pool as $i => $values): ?>
						<tr>
							<td><?=$values['key']; ?></td>
							<td class="word-wrap"><code><?=$values['value'];?></code></td>
							<td><?=Helpers\Format::formatBytes($values['size'],2);?></td>
							<td><?=$values['type']; ?></td>
							<td><a class="btn btn-danger" onclick="Common.confirm('Are you sure?', '/delete?key=<?=$values['key']; ?>'); return false;" href="#">X</a>
						</tr>
					<?php endforeach; ?>
					</tbody>
				</table>
			</div>
		</div>

		<div id="dashboard-statistics" name="statistics" class="row padding-15" style="visibility: hidden; position: absolute;">
			<div class="col-xs-12 col-md-12">
				<div class="row top20">

					<div class="col-xs-12 col-sm-6 col-md-6 col-lg-6">
						<div class="panel panel-default">
							<div class="panel-heading">
								<h3 class="panel-title">Hit/Miss</h3>
							</div>
							<div class="panel-body">
								<div id="hit_miss_cart" style="height: 250px; width: 350px"></div>
							</div>
						</div>
					</div>

					<div class="col-xs-12 col-sm-6 col-md-6 col-lg-6">
						<div class="panel panel-default">
							<div class="panel-heading">
								<h3 class="panel-title">Memory</h3>
							</div>
							<div class="panel-body">
								<div id="memory_cart" style="height: 250px; width: 350px"></div>
							</div>
						</div>
					</div>
				</div>
			</div>
		</div>

		<div id="dashboard-adapter" name="adapter" class="row padding-15" style="visibility: hidden; position: absolute;">
			<div class="table-responsive">
				<div class="panel-heading">
					<h4 class="panel-title">PHP <?=$title;?> config</h4>
				</div>
				<table class="table table-bordered table-hover table-striped" style="table-layout: fixed;">
					<tbody>
						<?php $i = 0; foreach ($adapter as $k => $v): ?>
							<?php if($i%2==0):?>
								<tr>
							<?php endif;?>
							<?php $i++; ?>
							<?="<td>",$k,"</td><td>",str_replace(',',',<br />',$v['local_value']),"</td>"; ?>
							<?php if($i%2==0):?>
								<tr>
							<?php endif;?>
						<?php endforeach;?>
					</tbody>
				</table>
			</div>
		</div>
	</div>
	<div class="clearfix"></div>
</div>
<script type="text/javascript">

		// Make all JS-activity for dashboard
		DashboardTabChecker();

		LoadMorrisScripts(function() {
			Morris.Donut({
				element: 'hit_miss_cart',
				data: [
					{label: "Hit", value: <?=$server['stats']['get_hits'] ?>},
					{label: "Miss", value: <?=$server['stats']['get_misses'] ?>},
				],
				colors: ['#5cb85c','#d9534f']
			});

			Morris.Bar({
				element: 'memory_cart',
				data: [
					{type: 'total',v: <?=number_format((real) $server['stats']['limit_maxbytes']/(1024*1024),3);?>},
					{type: 'used', v: <?=number_format((real) $server['stats']['bytes']/(1024*1024),3);?>},
					{type: 'read', v: <?=number_format((real) $server['stats']['bytes_read']/(1024*1024),3);?>},
					{type: 'sent', v: <?=number_format((real) $server['stats']['bytes_written']/(1024*1024),3);?>}
				],
				xkey: 'type',
				ykeys: ['v'],
				labels: ['MB'],
				barColors: function (row, series, type) {
					if (type === 'bar') {
						var colors = ['#f0ad4e', '#5cb85c', '#5bc0de', '#d9534f'];
						return colors[row.x];
					}
					else
						return '#000';
				},
				barRatio: 0.4,
				xLabelAngle: 35,
				hideHover: 'auto'
			});
		});

		LoadDataTablesScripts(function() {

			$("#stored_keys").dataTable({
				"aaSorting": [[ 0, "asc" ]],
				"bFilter":true,
				"bSort":true,
				"sPaginationType": "bootstrap",
				"sDom": "<'box-content'<'col-sm-6'f><'col-sm-6 text-right'l><'clearfix'>>rt<'box-content'<'col-sm-6'i><'col-sm-6 text-right'p><'clearfix'>>",
				"oLanguage": {
					"sSearch": "",
					"sLengthMenu": '_MENU_',
					"searchPlaceholder": 'Search...'
				}
			});
			$('.dataTables_filter input').attr("placeholder", "Search...");

		});
</script>