<div class="container-fluid">
	<div id="page-login" class="row">
		<div class="col-xs-12 col-md-4 col-md-offset-4 col-sm-6 col-sm-offset-3">
			<div class="box">
				<div class="box-content">
					<div class="text-center">
						<h3 class="page-header">Control Panel</h3>
						<p><?php $this->flash->output() ?></p>
					</div>
					<form action="" method="POST">
						<input type="hidden" name="<?php echo $this->security->getTokenKey() ?>"
							   value="<?php echo $this->security->getToken() ?>"/>
						<div class="form-group">
							<label class="control-label">Username</label>
							<input type="text" class="form-control" name="username" />
						</div>
						<div class="form-group">
							<label class="control-label">Password</label>
							<input type="password" class="form-control" name="password" />
						</div>
						<div class="form-group">
							<div class="checkbox-inline">
								<label>
									<input type="checkbox" name="remember"> Remember me
									<i class="fa fa-square-o"></i>
								</label>
							</div>
						</div>
						<div class="text-center">
							<input type="submit" class="btn btn-primary" value="Sign in">
						</div>
					</form>
				</div>
			</div>
		</div>
	</div>
</div>
