<?php echo $this->tag->stylesheetLink("assets/plugins/bootstrap-language/languages.min.css", true); ?>
<div id="footer_language_list">
    <ul ng-controller="LanguageController">
        <li>
            <span ng-click="changeLanguage('en')" class="lang-sm lang-lbl" lang="en"></span>&nbsp;
        </li>
        <li>
            <span ng-click="changeLanguage('ru')" class="lang-sm lang-lbl" lang="ru"></span>&nbsp;
        </li>
        <li>
            <span ng-click="changeLanguage('de')" class="lang-sm lang-lbl" lang="de"></span>&nbsp;
        </li>
    </ul>
</div>
