<!-- Block header -->
<div id="dashboard-header" class="row">
    <div class="col-xs-10 col-sm-4">
        <h3><i class="fa fa-bars fa-md"></i> <b><?= $title; ?></b></h3>
    </div>
    <div class="col-xs-10 col-sm-4">
        <div class="btn-group">
            <?= $this->tag->linkTo(['dashboard/categories/assign', 'Add category', 'class' => 'btn btn-primary']); ?>
            <?= $this->tag->linkTo(['dashboard/categories/rebuild', 'Rebuild tree', 'class' => 'btn btn-success']); ?>
        </div>
    </div>
</div>
<div class="clearfix"></div>
<!-- /Block header -->

<!-- Block content -->
<div class="row">
    <div class="col-xs-12">
        <div class="box no-border">
            <div class="box-header">
                <div class="box-name">
                    <i class="fa fa-table"></i>
                    <span>Categories Board</span>
                </div>
                <div class="box-icons">
                    <a class="collapse-link">
                        <i class="fa fa-chevron-up"></i>
                    </a>
                </div>
                <div class="no-move"></div>
            </div>
            <div class="box-content no-padding">
                <table id="table" cellspacing="0" class="table table-bordered table-striped table-hover table-heading table-datatable">
                    <thead>
                    <tr>
                        <th class="col-md-2">Category</th>
                        <th class="col-md-5">Description</th>
                        <th class="col-md-1">Parent</th>
                        <th class="col-md-1">Alias</th>
                        <th class="col-md-1">Sort</th>
                        <th class="col-md-1">Manage</th>
                    </tr>
                    </thead>
                    <tbody>
                    </tbody>
                </table>
            </div>
        </div>
    </div>
</div>
<!-- Block content -->
<script type="text/javascript">

    $(function () {

        LoadDataTablesScripts(function () {

            $('#table').DataTable({
                serverSide: true,
                paginate: true,
                ajax: {
                    url: '/dashboard/categories',
                    method: 'POST'
                },
                "sDom": "<'box-content'<'col-sm-6'f><'col-sm-6 text-right'l><'clearfix'>>rt<'box-content'<'col-sm-6'i><'col-sm-6 text-right'p><'clearfix'>>",
                "oLanguage": {
                    "sSearch": "",
                    "info": "Showing _START_ to _END_ of _TOTAL_ entries",
                    "sLengthMenu": '_MENU_'
                },
                "aLengthMenu": [[10, 25, 50, -1], [10, 25, 50, "All"]],

                columns: [
                    {data: "title", targets: "1"},
                    {data: "description", targets: "2"},
                    {data: "parent_id", targets: "3"},
                    {data: "alias", targets: "4"},
                    {data: "sort", targets: "5" , searchable: false},
                    {data: null, targets: "6" , searchable: false, orderable: false, render: function(obj){
                        return '<div class="btn-group">' +
                        '<a class="btn btn-primary" href="<?= $this->url->get(['for' => 'dashboard-full', 'controller' => $this->router->getControllerName(), 'action' => 'edit']); ?>id/'+obj.id+'">' +
                        '<i class="fa fa-pencil-square-o fa-fw"></i> Edit' +
                        '</a>' +
                        '<a class="btn btn-primary dropdown-toggle" data-toggle="dropdown" href="#">' +
                        '<span class="fa fa-caret-down fa-mf"></span>' +
                        '</a>' +
                        '<ul class="dropdown-menu">' +
                        '<li>' +
                        '<a onclick="Common.confirm(\'Are you sure want to delete this category?<br> The procedure provided a not predictable consequences\', this.href); return false;" href="<?= $this->url->get(['for' => 'dashboard-full', 'controller' => $this->router->getControllerName(), 'action' => 'delete']); ?>id/'+obj.id+'">' +
                        '<i class="fa fa-trash-o fa-fw"></i> Delete' +
                        '</a>' +
                        '</li>' +
                        '<li>' +
                        '<a href="<?= $this->url->get(['for' => 'dashboard-full', 'controller' => $this->router->getControllerName(), 'action' => 'enable']); ?>id/'+obj.id+'">' +
                        '<i class="fa fa-unlock-alt fa-fw"></i> Enable' +
                        '</a>' +
                        '</li>' +
                        '<li>' +
                        '<a href="<?= $this->url->get(['for' => 'dashboard-full', 'controller' => $this->router->getControllerName(), 'action' => 'disable']); ?>id/'+obj.id+'">' +
                        '<i class="fa fa-lock fa-fw"></i> Disable' +
                        '</a>' +
                        '</li>' +
                        '</ul>' +
                        '</div>'
                    }}
                ],
                "sPaginationType": "full_numbers",
                "language": {
                    "emptyTable": "No records found"
                }
            });
            $('label input[type=search]').attr('placeholder', 'Search category...');
        });
    });
</script>
