<!-- Block header -->
<div id="dashboard-header" class="row">
    <div class="col-xs-10 col-sm-4">
        <h3><i class="fa fa-bars fa-md"></i> <b><?= $title; ?></b></h3>
    </div>
    <div class="col-xs-10 col-sm-4">
        <div class="btn-group">
            <?= $this->tag->linkTo(['dashboard/categories/assign', 'Add category', 'class' => 'btn btn-primary']); ?>
            <?= $this->tag->linkTo(['dashboard/categories/rebuild', 'Rebuild tree', 'class' => 'btn btn-success']); ?>
        </div>
    </div>
</div>
<div class="clearfix"></div>
<!-- /Block header -->

<!-- Block content -->
<div class="row">
    <div class="col-xs-12">
        <div class="box no-border">
            <div class="box-header">
                <div class="box-name">
                    <i class="fa fa-table"></i>
                    <span>Categories Board</span>
                </div>
                <div class="box-icons">
                    <a class="collapse-link">
                        <i class="fa fa-chevron-up"></i>
                    </a>
                </div>
                <div class="no-move"></div>
            </div>
            <div class="box-content no-padding">
                <table id="table" cellspacing="0"
                       class="table table-bordered table-striped table-hover table-heading table-datatable">
                    <thead>
                    <tr>
                        <th class="col-md-2">Category</th>
                        <th class="col-md-3">Description</th>
                        <th class="col-md-1">Parent</th>
                        <th class="col-md-2">Alias</th>
                        <th class="col-md-1">Sort</th>
                        <th class="col-md-2">Manage</th>
                    </tr>
                    </thead>
                    <tbody>
                    </tbody>
                </table>
            </div>
        </div>
    </div>
</div>
<!-- Block content -->
<script type="text/javascript">

    $(function () {

        LoadDataTablesScripts(function () {

            $('#table').DataTable({
                serverSide: true,
                paginate: true,
                ajax: {
                    url: '/dashboard/categories',
                    method: 'POST'
                },
                "sDom": "<'box-content'<'col-sm-6'f><'col-sm-6 text-right'l><'clearfix'>>rt<'box-content'<'col-sm-6'i><'col-sm-6 text-right'p><'clearfix'>>",
                "oLanguage": {
                    "sSearch": "",
                    "info": "Showing _START_ to _END_ of _TOTAL_ entries",
                    "sLengthMenu": '_MENU_'
                },
                "aLengthMenu": [[10, 25, 50, -1], [10, 25, 50, "All"]],
                columns: [
                    {data: "title"},
                    {data: "description"},
                    {data: "parent_id"},
                    {data: "alias"},
                    {data: "sort", searchable: false}
                ],
                "columnDefs": [{
                    "targets": 5,
                    "data": null,
                    "render": function(obj){
                        console.log(obj);
                        return "<input id='" + obj.id + "' type='text' value='myval'/>"
                    }
                }],
                "sPaginationType": "full_numbers",
                "language": {
                    "emptyTable":     "No records found"
                }
            });
            $('label input[type=search]').attr('placeholder', 'Search...');
        });
    });
</script>
