<!-- Block header -->
<div id="dashboard-header" class="row">
	<div class="col-xs-10 col-sm-4">
		<h3><i class="fa fa-tachometer fa-md"></i> <b><?=$title;?></b></h3>
	</div>
	<div class="col-xs-10 col-sm-4">
		<div class="btn-group">
			<?=$this->tag->linkTo(['dashboard/engines/add', 'Add engine', 'class' => 'btn btn-primary']); ?>
		</div>
	</div>
</div>
<div class="clearfix"></div>
<!-- /Block header -->

<!-- Block content -->
<div class="row">
	<div class="col-xs-12">
		<div class="box-name">
			<i class="fa fa-table"></i>
			<span>Engines Board</span>
		</div>
		<div class="box-conten no-paddingt">
			<table id="table" class="table table-striped table-bordered table-hover table-heading no-border-bottom">
				<thead>
				<tr>
					<th class="col-md-1">ID</th>
					<th class="col-md-1">Host</th>
					<th class="col-md-1">Name</th>
					<th class="col-md-1">Code</th>
					<th class="col-md-1">Currency</th>
					<th class="col-md-1">Status</th>
					<th class="col-md-2">Added</th>
					<th class="col-md-2">Action</th>
				</tr>
				</thead>
				<tbody>
				<?php  foreach($items as $item): ?>
					<tr>
						<td><?=$item->getId();?></td>
						<td><?=$item->getHost();?></td>
						<td><?=$item->getName();?></td>
						<td><?=$item->getCode();?></td>
						<td><?=$item->currencyRel->getSymbol();?></td>
						<td><?=$item->getStatus();?></td>
						<td><?=\Helpers\Format::getFormatTime($item->getDateCreate());?></td>
						<td>
							<div class="btn-group">
								<a class="btn btn-primary" href="<?=$this->url->get(['for' => 'dashboard-full','controller' => $this->router->getControllerName(),'action' => 'view','params' => $item->getId()]); ?>">
									<i class="fa fa-paper-plane-o"></i> view
								</a>
								<a class="btn btn-primary dropdown-toggle" data-toggle="dropdown" href="#">
									<span class="fa fa-caret-down"></span></a>
								<ul class="dropdown-menu">
									<li>
										<a href="<?=$this->url->get(['for' => 'dashboard-full','controller' => $this->router->getControllerName(),'action' => 'edit','params' => $item->getId()]); ?>">
											<i class="fa fa-pencil-square-o fa-fw"></i> Edit
										</a>
									</li>
									<li>
										<a href="<?=$this->url->get(['for' => 'dashboard-full','controller' => $this->router->getControllerName(),'action' => 'delete','params' => $item->getId()]); ?>">
											<i class="fa fa-trash-o fa-fw"></i> Delete
										</a>
									</li>
									<li>
										<a href="<?=$this->url->get(['for' => 'dashboard-full','controller' => $this->router->getControllerName(),'action' => 'status','params' => $item->getId()]); ?>">
											<i class="fa fa-flag-0 fa-fw"></i> Status
										</a>
									</li>
								</ul>
							</div>
						</td>
					</tr>
				<?php endforeach;?>
				</tbody>
			</table>
		</div>
	</div>
</div>
<!-- Block content -->
<script type="text/javascript">

	LoadDataTablesScripts(function() {

		$("#table").dataTable({
			"bSort"				:	true,
			"paginate"	: 	false,
			"info"	: 	false,
			"filter"		: false
		});
	});
</script>
