<!-- Block header -->
<div id="dashboard-header" class="row">
	<div class="col-xs-10 col-sm-4">
		<h3><i class="fa fa-tachometer fa-md"></i> <b><?=$title;?></b></h3>
	</div>
	<div class="col-xs-10 col-sm-4">
		<div class="btn-group">
			<?=$this->tag->linkTo(['dashboard/engines/add', 'Add engine', 'class' => 'btn btn-primary']); ?>
		</div>
	</div>
</div>
<div class="clearfix"></div>
<!-- /Block header -->

<!-- Block content -->
<div class="row">
	<div class="col-xs-12">
		<div class="box-name">
			<i class="fa fa-table"></i>
			<span>Content Management Systems</span>
		</div>
		<div class="box-conten no-paddingt">
			<table id="engines" class="table table-striped table-bordered table-hover table-heading no-border-bottom">
				<thead>
				<tr>
					<th class="col-md-1">ID</th>
					<th class="col-md-1">Host</th>
					<th class="col-md-1">Name</th>
					<th class="col-md-1">Code</th>
					<th class="col-md-1">Currency</th>
					<th class="col-md-1">Status</th>
					<th class="col-md-2">Added</th>
					<th class="col-md-2">Action</th>
				</tr>
				</thead>
				<tbody>
				<?php  foreach($items as $item): ?>
					<tr>
						<td><?=$item->getId();?></td>
						<td><?=$item->getHost();?></td>
						<td><?=$item->getName();?></td>
						<td><?=$item->getCode();?></td>
						<td><?=$item->currencyRel->getSymbol();?></td>
						<td><?=$item->getStatus();?></td>
						<td><?=\Helpers\Format::getFormatTime($item->getDateCreate());?></td>
						<td>
							<div class="btn-group">
								<a class="btn btn-primary" href="#"><i class="fa fa-user fa-fw"></i> User</a>
								<a class="btn btn-primary dropdown-toggle" data-toggle="dropdown" href="#">
									<span class="fa fa-caret-down"></span></a>
								<ul class="dropdown-menu">
									<li><a href="#"><i class="fa fa-pencil fa-fw"></i> Edit</a></li>
									<li><a href="#"><i class="fa fa-trash-o fa-fw"></i> Delete</a></li>
									<li><a href="#"><i class="fa fa-ban fa-fw"></i> Ban</a></li>
									<li class="divider"></li>
									<li><a href="#"><i class="i"></i> Make admin</a></li>
								</ul>
							</div>
						</td>
					</tr>
				<?php endforeach;?>
				</tbody>
			</table>
		</div>
	</div>
</div>
<!-- Block content -->

<script type="text/javascript">
	// Run Datables plugin and create 3 variants of settings
	function AllTables(){
		TestTable1();
		LoadSelect2Script(MakeSelect2);
	}
	function MakeSelect2(){
		$('select').select2();
		$('.dataTables_filter').each(function(){
			$(this).find('label input[type=text]').attr('placeholder', 'Search');
		});
	}
	$(document).ready(function() {
		// Load Datatables and run plugin on tables
		LoadDataTablesScripts(AllTables);
		// Add Drag-n-Drop feature
		WinMove();
	});
</script>
