<?php if(empty($message) === false): ?>
    <!-- Flash messenger -->
    <div class="alert alert-danger">
        <?=$message;?>
    </div>
    <!-- /Flash messenger -->
<?php endif; ?>

<!-- Block header -->
<div id="dashboard-header" class="row">
    <div class="col-xs-10 col-sm-4">
        <h3><i class="fa fa-search fa-md"></i> <b><?= $title; ?></b></h3>
    </div>
</div>
<div class="clearfix"></div>
<!-- /Block header -->

<!-- Block content -->
<div class="row">
    <div class="col-xs-12">
    </div>
</div>
<!-- Block content -->
<script type="text/javascript">
    $(function () {

    });
</script>
