<?php
    $services = $develop->getDi();
?>
<div id='pdw-panel-services' class='pdw-panel services'>
    <div class='title'>
        <h2>Loaded services<a class='pdw-panel-close'>&times;</a></h2>
    </div>
    <div class='panel-content'>
        <?php if(!empty($services)): ?>
            <?php  foreach ($services as $type => $services): ?>
                <?php if($type === '_services'): ?>
                    <h3 class='collapser'><?=ucfirst(substr($type, 1));?></h3>
                    <table class='pdw-data-table'>
                        <thead>
                        <tr>
                            <th>Alias</th>
                            <th>Class</th>
                        </tr>
                        </thead>
                        <tbody>
                            <?php foreach($services as $name => $variables): ?>
                                <tr>
                                    <td><?=$name?></td>
                                    <td><?=var_dump($variables);?></td>
                                </tr>
                            <?php endforeach; ?>
                        </tbody>
                    </table>
                <?php endif; ?>
            <?php endforeach; ?>
        <?php endif; ?>

    </div>
</div>
