<div class="pdw-wrap">
    <a id='pdw-icon'></a>

    <div id='pdw-toolbar'>
        <ul id='pdw-main-nav'>
            <li>
                <a href='#server'>
                    Server<br/>
                    <small>Engine PHP: <?php echo phpversion(); ?></small><br>
                    <small>Phalcon: <?php echo \Phalcon\Version::get(); ?></small>
                </a>
            </li>
            <li>
                <a href='#extensions'>
                    Extensions<br/>
                    <small>Loaded: <?php echo sizeof(get_loaded_extensions()); ?></small>
                </a>
            </li>
            <?php if (extension_loaded('geoip')): ?>
                <li>
                    <a href='#'>
                        Geo<br/>
                        <small>Database: <?php echo geoip_database_info(); ?></small>
                    </a>
                </li>
            <?php endif; ?>
            <li>
                <a href='#request'>
                    Request
                </a>
            </li>
            <li>
                <a href='#views'>
                    Views<br/>
                    <small><?php echo count($develop->getRenderedViews()); ?> rendered</small>
                </a>
            </li>
            <li>
                <a href='#db'>
                    Database<br/>
                    <small><?php echo $develop->getQueryCount(); ?> queries</small>
                </a>
            </li>
        </ul>
        <?php
        $panels = $develop->getPanels();
        foreach ($panels as $panel) {
            $this->partial("panels/{$panel}");
        }
        ?>
        <div id='pdw-resources'>
            <h3 class='title'>Resource Usage</h3>
            <table>
                <tbody>
                <tr>
                    <td>load time</td>
                    <td><?php echo round(($develop->getEndTime() - $develop->getStartTime()), 6); ?> s</td>
                </tr>
                <tr>
                    <td>elapsed time</td>
                    <td><?php echo round(($develop->getEndTime() - $_SERVER['REQUEST_TIME']), 6); ?> s</td>
                </tr>
                <tr>
                    <td>mem</td>
                    <td><?php echo number_format(memory_get_usage() / 1024, 2); ?> KB</td>
                </tr>
                <tr>
                    <td>mem peak</td>
                    <td><?php echo number_format(memory_get_peak_usage() / 1024, 2); ?> KB</td>
                </tr>
                <tr>
                    <td>session size</td>
                    <?php if (isset($_SESSION)): ?>
                        <td><?php printf('%0.3F KB', mb_strlen(serialize($_SESSION)) / 1024); ?></td>
                    <?php else: ?>
                        <td>0</td>
                    <?php endif ?>
                </tr>
                </tbody>
            </table>
        </div>
    </div>
</div>
<?= $this->tag->stylesheetLink('assets/debug/informer/css/style.css', true); ?>
<?= $this->tag->stylesheetLink('assets/debug/informer/lib/prism/prism.css', true); ?>
<?= $this->tag->javascriptInclude("assets/debug/informer/lib/prism/prism.js", true);  // local  ?>
<?= $this->tag->javascriptInclude("assets/debug/informer/js/pdw-ck.js", true);  // local  ?>
